In [5]:
import pandas as pd 
import numpy as np 

In [6]:
df = pd.read_csv('spam.csv', encoding='ISO-8859-1') 
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [8]:
df.v1.value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [9]:
df['spam']= df['v1'].apply(lambda x : 1 if x=='spam' else 0) 

In [10]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  spam  
0        NaN        NaN     0  
1        NaN        NaN     0  
2        NaN        NaN     1  
3        NaN        NaN     0  
4        NaN        NaN     0

In [11]:
from sklearn.model_selection import train_test_split 
X_train, X_test,y_train, y_test = train_test_split(df.v2,df.spam, test_size=0.2)

In [12]:
X_train.shape

(4457,)

In [13]:
X_test.shape

(1115,)

In [14]:
type(X_train)

pandas.core.series.Series

In [17]:
X_train[:4]

5561    Get me out of this dump heap. My mom decided t...
3435    If india win or level series means this is rec...
3996    Bored housewives! Chat n date now! 0871750.77....
824                             Have a good evening! Ttyl
Name: v2, dtype: object

In [18]:
type(y_train)

pandas.core.series.Series

In [19]:
y_train[:4]

5561    0
3435    0
3996    1
824     0
Name: spam, dtype: int64

In [20]:
type(X_train.values)

numpy.ndarray

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_cv= v.fit_transform(X_train.values)
X_train_cv

<4457x7743 sparse matrix of type '<class 'numpy.int64'>'
	with 59373 stored elements in Compressed Sparse Row format>

In [22]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [23]:
X_train_cv.shape

(4457, 7743)

In [24]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'ûïharry', 'ûò', 'ûówell'],
      dtype=object)

In [25]:
v.get_feature_names_out().shape

(7743,)

In [26]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',

In [50]:
v.vocabulary_

{'am': 945,
 'in': 3674,
 'office': 4933,
 'whats': 7512,
 'the': 6864,
 'matter': 4419,
 'msg': 4649,
 'me': 4438,
 'now': 4873,
 'will': 7548,
 'call': 1615,
 'you': 7740,
 'at': 1128,
 'break': 1499,
 'urgent': 7246,
 'we': 7457,
 'are': 1058,
 'trying': 7109,
 'to': 6984,
 'contact': 1994,
 'last': 4062,
 'weekends': 7477,
 'draw': 2466,
 'shows': 6175,
 'that': 6859,
 'have': 3384,
 'won': 7604,
 '900': 729,
 'prize': 5463,
 'guaranteed': 3293,
 '09061701939': 201,
 'claim': 1838,
 'code': 1892,
 's89': 5907,
 'valid': 7281,
 '12hrs': 297,
 'only': 4981,
 'awake': 1179,
 'oh': 4943,
 'what': 7510,
 'up': 7226,
 'tried': 7088,
 're': 5633,
 'your': 7745,
 'reply': 5761,
 'our': 5043,
 'offer': 4930,
 'of': 4925,
 'video': 7322,
 'phone': 5224,
 '750': 622,
 'anytime': 1011,
 'any': 1002,
 'network': 4780,
 'mins': 4527,
 'half': 3329,
 'price': 5447,
 'line': 4162,
 'rental': 5748,
 'camcorder': 1634,
 'or': 5010,
 '08000930705': 49,
 'haha': 3321,
 'mayb': 4431,
 'rite': 5839,
 'k

In [27]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
np.where(X_train_np[0]!=0)

(array([1425, 1893, 2182, 2478, 3114, 3371, 4218, 4387, 4548, 4654, 4888,
        5008, 6845, 6930], dtype=int64),)

In [30]:
X_train[:4]

5561    Get me out of this dump heap. My mom decided t...
3435    If india win or level series means this is rec...
3996    Bored housewives! Chat n date now! 0871750.77....
824                             Have a good evening! Ttyl
Name: v2, dtype: object

In [31]:
X_train_np[0][4438]

0

In [32]:
v.get_feature_names_out()[4438]

'mesages'

In [33]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [34]:
X_test_cv = v.transform(X_test)    

In [35]:
from sklearn.metrics import classification_report 
y_pred = model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       978
           1       0.98      0.92      0.95       137

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [36]:
from sklearn.pipeline import Pipeline 
clf = Pipeline([('vectorizer', CountVectorizer()), 
               ('nb', MultinomialNB())])

In [37]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [38]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))    

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       978
           1       0.98      0.92      0.95       137

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [39]:
#exercise 
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [41]:
df = pd.read_csv('IMDB Dataset.csv', encoding='ISO-8859-1') 
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [43]:
df = pd.read_csv("IMDB Dataset.csv")

In [49]:
from sklearn.pipeline import Pipeline
clf = Pipeline([ ('vectorizer' , CountVectorizer()),
                ('random_forest', (RandomForestClassifier(n_estimators=50, criterion='entropy'))
                )])
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       978
           1       1.00      0.80      0.89       137

    accuracy                           0.98      1115
   macro avg       0.99      0.90      0.94      1115
weighted avg       0.98      0.98      0.97      1115

